import { Module } from "@nestjs/common";
import { TypeOrmExModule } from "../../../modules";
import { ZoomModule } from "../zoom/zoom.module";
import {
    AssessmentController,
    ClassRoomController,
    ClassScheduleController,
    ClassSubjectController,
    CommonController,
    GradeController,
    StudentController,
    TutorController,
} from "./controllers";
import { AssessmentSubmissionController } from "./controllers/assessment-submission.controller";
import {
    Area,
    Assessment,
    AssessmentSubmission,
    ChatRoom,
    ClassRoom,
    ClassSchedule,
    ClassScheduleHistory,
    ClassStudent,
    ClassSubject,
    Grade,
    Message,
    MessageUserStatus,
    Payment,
    Tutor,
} from "./entities";
import {
    AreaRepository,
    AssessmentRepository,
    ChatRoomRepository,
    ClassRoomRepository,
    ClassScheduleHistoryRepository,
    ClassScheduleRepository,
    ClassStudentsRepository,
    ClassSubjectRepository,
    GradeRepository,
    MessageRepository,
    MessageUserStatusRepository,
    PaymentRepository,
    TutorRepository,
} from "./repositories";
import { AssessmentSubmissionRepository } from "./repositories/assessment-submission.repository";
import {
    AreaService,
    AssessmentService,
    AssessmentSubmissionService,
    ChatRoomService,
    ClassRoomService,
    ClassSubjectService,
    GradeService,
    MessageService,
    PaymentService,
    ScheduleService,
    StudentService,
    TutorService,
} from "./services";

@Module({
    imports: [
        TypeOrmExModule.forCustomRepository([
            ClassRoom,
            ClassRoomRepository,
            ClassStudent,
            ClassStudentsRepository,
            Grade,
            GradeRepository,
            Payment,
            PaymentRepository,
            ClassSchedule,
            ClassScheduleRepository,
            ClassScheduleHistory,
            ClassScheduleHistoryRepository,
            ClassSubject,
            ClassSubjectRepository,
            Tutor,
            TutorRepository,
            Area,
            AreaRepository,
            ChatRoom,
            ChatRoomRepository,
            Message,
            MessageRepository,
            MessageUserStatus,
            MessageUserStatusRepository,
            Assessment,
            AssessmentRepository,
            AssessmentSubmission,
            AssessmentSubmissionRepository,
        ]),
        ZoomModule,
    ],
    controllers: [
        CommonController,
        ClassRoomController,
        GradeController,
        ClassScheduleController,
        ClassSubjectController,
        StudentController,
        TutorController,
        AssessmentController,
        AssessmentSubmissionController,
    ],
    providers: [
        ClassRoomService,
        GradeService,
        ScheduleService,
        TutorService,
        ClassSubjectService,
        AreaService,
        StudentService,
        PaymentService,
        ChatRoomService,
        MessageService,
        AssessmentService,
        AssessmentSubmissionService,
    ],
})
export class ClassRoomModule {}
