// noinspection JSUnusedGlobalSymbols

export enum Permission {
    ROLE_GET = "ROLE_GET",
    ROLE_GET_PERMISSIONS = "ROLE_GET_PERMISSIONS",
    ROLE_LIST = "ROLE_LIST",
    ROLE_VIEW = "ROLE_VIEW",
    ROLE_CREATE = "ROLE_CREATE",
    ROLE_UPDATE_PERMISSIONS = "ROLE_UPDATE_PERMISSIONS",
    ROLE_UPDATE_STATUS = "ROLE_UPDATE_STATUS",
    ROLE_DELETE = "ROLE_DELETE",
    ROLE_WIPE = "ROLE_WIPE",

    USER_GET = "USER_GET",
    USER_LIST = "USER_LIST",
    USER_VIEW = "USER_VIEW",
    USER_CREATE = "USER_CREATE",
    USER_UPDATE = "USER_UPDATE",
    USER_UPDATE_ROLE = "USER_UPDATE_ROLE",
    USER_UPDATE_STATUS = "USER_UPDATE_STATUS",
    USER_DELETE = "USER_DELETE",
    USER_WIPE = "USER_WIPE",

    PROFILE_GET = "PROFILE_GET",
    PROFILE_LIST = "PROFILE_LIST",
    PROFILE_VIEW = "PROFILE_VIEW",
    PROFILE_CREATE = "PROFILE_CREATE",
    PROFILE_UPDATE = "PROFILE_UPDATE",
    PROFILE_UPDATE_ROLE = "PROFILE_UPDATE_ROLE",
    PROFILE_UPDATE_STATUS = "PROFILE_UPDATE_STATUS",
    PROFILE_DELETE = "PROFILE_DELETE",
    PROFILE_WIPE = "PROFILE_WIPE",
}
