export * from "./class-room.repository.interface";
export * from "./class-student.repository.interface";
export * from "./grade.repository.interface";
export * from "../../../payment/interfaces/repositories/payment.repository.interface";
export * from "./schedule.repository.interface";
export * from "./schedule-history.repository.interface";
export * from "./subject.repository.interface";
export * from "./tutor.repository.interface";
export * from "./area.repository.interface";
